# Generated by Django 4.2.7 on 2025-06-13 10:51

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='login_settings_logos')),
                ('company_name', models.CharField(default='TRUE BIT', max_length=100)),
                ('first_part_text', models.CharField(default='TRUE', max_length=50)),
                ('second_part_text', models.CharField(default='BIT', max_length=50)),
                ('first_part_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('second_part_color', models.CharField(default='#FF6B6B', max_length=20)),
                ('subtitle', models.CharField(default='TECHNOLOGIES & INVENTIONS PVT.LTD', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_settings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Page Settings',
                'verbose_name_plural': 'Login Page Settings',
            },
        ),
    ]
