# Generated by Django 4.2.7 on 2025-05-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
