# Generated by Django 4.2.7 on 2025-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_is_return_purchase_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
