# Generated by Django 4.2.7 on 2025-05-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'Purchase Item', 'verbose_name_plural': 'Purchase Items'},
        ),
    ]
