# Generated by Django 4.2.7 on 2025-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchase_options_alter_purchaseitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('returned', 'Returned')], default='completed', max_length=10),
        ),
    ]
