# Generated by Django 4.2.7 on 2025-06-13 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_registration_image_alter_store_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PURCHASE', 'Purchase Report'), ('PURCHASE_RETURN', 'Purchase Return Report'), ('SALE', 'Sale Report'), ('SALE_RETURN', 'Sale Return Report')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word Document'), ('XLSX', 'Excel Spreadsheet')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.store')),
            ],
        ),
    ]
