# Generated by Django 4.2.7 on 2025-06-13 12:03

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_registration_image_alter_store_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload store photo (jpg, jpeg, png only)', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='store_photos'),
        ),
    ]
