# Generated by Django 4.2.7 on 2025-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
