# Generated by Django 4.2.7 on 2025-06-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_saleitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='Sales.sale'),
        ),
    ]
