# Generated by Django 4.2.7 on 2025-06-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_sale_original_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.sale'),
        ),
    ]
